IP        = "10.42.0.157"
bitfile   = "spec_1in_2048ch_983mhz_real.fpg"
adc_bits  = 14

[snapshots]
snap_names = ["adc_snapshot"]
n_samples = 256

[spectra]
bram_names = [["spec0", "spec1", "spec2", "spec3"]]
addr_width = 9
data_width = 64
bandwidth  = 983.04
reset_reg  = "cnt_rst"
acc_reg    = "acc_len"
acc_len    = 65536
